### ISSUE TITLE
Hanging in installing screen and does not proceed.

### ISSUE THREAD

**Issue by etulfnap** [myflashlab/ANE-LAB#14] opened 2018-02-12 15:28 UTC
Hi, thanks for the program. and updates.

During the installation of ANE (permission dependencies), it just stuck and not proceed.
I tried to capture each steps I went through.   And I upladed the project package.
[https://drive.google.com/file/d/1YzMlYamptwx-4W5y-k2X_lSXVnakVgaZ/view?usp=sharing](url)
By the way, could you please tell me where can I find log.txt? I want to open it and see what's going on.

![image](https://user-images.githubusercontent.com/1762095/36103872-7436949e-104b-11e8-8689-3a2341f3d4ff.png)
![image](https://user-images.githubusercontent.com/1762095/36103889-7fd53e9a-104b-11e8-8beb-eb397864ee62.png)
![image](https://user-images.githubusercontent.com/1762095/36103900-88161a8e-104b-11e8-9fe5-0d3db087966b.png)
![image](https://user-images.githubusercontent.com/1762095/36103909-8ee76430-104b-11e8-9da0-dca01d87fa75.png)

**#Stuck at this screen.**

![image](https://user-images.githubusercontent.com/1762095/36103919-93cf5c00-104b-11e8-988e-c277776593a2.png)

**# Files that are downloaded.**
![image](https://user-images.githubusercontent.com/1762095/36103929-98acde00-104b-11e8-953b-769b66ad79af.png)

**Comment by myflashlab** [comment] 2018-02-12 20:16
Thanks for the detailed description. update to V1.1.11 and this bug will be killed. The problem was that your manifest file didn't have an ```<application>``` tag under the ```android``` tag. Although this is unusual, but from now on, ANELAB will identify this and adds it automatically. cheers.

While trying to reproduce the bug according to your description, we also found another minor bug (you are using Android build only but the permission ANE will force you to enter usage description for iOS! this is not a big deal because the final manifest compilation will NOT include the iOS part anyhow but it is better to have it fixed) which will also be fixed in future releases. the current halting bug is fixed now anyway. Enjoy using ANELAB and thanks for helping us improving it.

**Closed by myflashlab** 2018-02-12 20:16 UTC

**Comment by myflashlab** [comment] 2018-02-12 20:25
> By the way, could you please tell me where can I find log.txt?

its on your computer's ```Documents``` directory. the folder name is "ANELAB_LOGS"

**Comment by etulfnap** [comment] 2018-02-13 09:46
OMG.. you guys are awesome!!  Thanks for the quickest update I have ever seen. 👍 👍
